pipeline {
    agent any
    environment {
        EXAMPLE_CREDS = credentials('github-user-psw')
    }
    stages {
        stage('Example') {
            steps {
                /* WRONG! */
                bat("curl -u ${EXAMPLE_CREDS_USR}:${EXAMPLE_CREDS_PSW} https://github.com/bikarnap/something_nothing")
            }
        }
    }
}